# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Viper-Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Viper-Sample
  pod 'Alamofire', '~> 5.0.0-beta.3'

  target 'Viper-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
